### PR TITLE
added profile button to home page if user logged in

### LINKED ISSUE #225: After login remove Login button from home page
### **User story**
**Who**: User
**What**: I don't want to to see the Login button once after I login 
**Why**:  As per requirement we don’t have Login button after login

### **Acceptance criteria**

- first login from the home page

Screenshot 2021-05-31 at 16 39 02

- Still we can see Login button after login

Screenshot 2021-05-31 at 16 40 04

### PR DESCRIPTION
**Pull request by rajanibusani**
# Description
Added My profile to home, if user is logged in, and also in profile page changed the end point, which we are using to get the user information

Please provide a short summary explaining what this PR is about.

Fixes #225

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by ccshah298 — APPROVED** [review]
👍its looks ok to me.

**Review by DlnyaMazhari — APPROVED** [review]

**Review by sandhana14 — APPROVED** [review]
Looks good @rajanibusani 👍

**Review by ditlevHYF — APPROVED** [review]
Looks good! Works as it should on my machine. I can see the google login changing to my profile link, and when I update the page, im still shown the profile. Good work

**Comment by rajanibusani** [comment]
> Looks good! Works as it should on my machine. I can see the google login changing to my profile link, and when I update the page, im still shown the profile. Good work

Thank You @ditlevHYF

**Pull request merged**
