### PR TITLE
changed some styling in different files for the homepage

### PR DESCRIPTION
**Pull request by TITHI1244**
# Description

changed some styling in different files for the homepage

Fixes # (issue)
1. The homepage was not one-page, needed to scroll down
2. Missing text-shadow for the app heading
3. Missing buttons shadow

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by DlnyaMazhari** [comment]
homepage

thanks @TITHI1244  but few things to mention :
box sizes don't match

**Comment by DlnyaMazhari** [comment]
homepagee

In here, the font is very small.

**Comment by DlnyaMazhari** [comment]
1920x1080

and in size 1920 x 1080 , the font sizes are very small

**Comment by TITHI1244** [comment]
> homepage
> 
> thanks @TITHI1244 but few things to mention :
> box sizes don't match

Yes, that I saw but ignored. Don't have much time now. Need to fix a few more pages. Actually it's taking long time as it involves many pages and there are lots of fixed styling here and there, in px. Will try to fix it if I can manage others. Thanks.

**Review by rajanibusani — COMMENTED** [review]
Hi Tithi...after clicking the burger menu, side bar is not showing, Can u check that once

**Review by Enqira — CHANGES_REQUESTED** [review]
Hello Tithi, thank you for your time and the effort that you have put in, here is my review:
1- your commit message is "changed some styles in different files", could you be more precise of what the commit is solving solving?
2- In the description you say that you are solving 3 issues, but you have redone all styles of homepage in the code.
3- In the description, issue number 1 you say that you are solving the scrolling, it was already scrolling, but only if there is not enough space for all the elements.
4- Maybe you have solved some problems with the homepage, but you have also created new problems.
Conclution: We have the presentation tomorrow, the PR is too big, my feedback is that you create a new one, pick just one or two small issues that you want to solve, be precise and solve them. It is too late to experiment now.

**Review by rajanibusani — APPROVED** [review]
Good job @TITHI1244

**Comment by TITHI1244** [comment]
Closing this PR as I did it in a rush and it was incomplete.

**Pull request closed without merging**
