### PR TITLE
added email registration form component with storybook

### PR DESCRIPTION
**Pull request by rajanibusani**
# Description

Added form with email input and button and when user clicks without entering email or if enters an invalid email, user will get an 
error message and warning icon 

Fixes # (issue)
#40 

# How to test?
using npm run storybook and **To check error message and sign give a wrong email by entering wrongly .com i.e .om or .cm...**
# Checklist
- [✓] I have performed a self-review of my own code
- []✓ I have commented my code, particularly in hard-to-understand areas
- [✓] I have made corresponding changes to the documentation
- [✓] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by TITHI1244 — COMMENTED** [review]
Nice code with easy-to-understand comments @rajanibusani :) I have a suggestion though. When an error happens and error message appears, should the email-container have also an orange border instead of black? And an orange ! sign at right? I thought it from the figma image.

**Comment by rajanibusani** [comment]
> Nice code with easy-to-understand comments @rajanibusani :) I have a suggestion though. When an error happens and error message appears, should the email-container have also an orange border instead of black? And an orange ! sign at right? I thought it from the figma image.

@TITHI1244 yes..tithi, i did that, when user enter an email like xyz@gmail.om (not .com), the user will get an orange sign and warning, but i didnt put them for when the user enters continue without entering email,as i am not sure about that case.., but let me know, if have to do something else too, i will do that..!

**Comment by rajanibusani** [comment]
> # Description
> Added form with email input and button and when user clicks without entering email or if enters an invalid email, user will get an
> error message and warning icon
> 
> Fixes # (issue)
> #40
> 
> # How to test?
> using npm run storybook
> 
> # Checklist
> * [✓] I have performed a self-review of my own code
> * []✓ I have commented my code, particularly in hard-to-understand areas
> * [✓] I have made corresponding changes to the documentation
> * [✓] This PR is ready to be merged and not breaking any other functionality



> > Nice code with easy-to-understand comments @rajanibusani :) I have a suggestion though. When an error happens and error message appears, should the email-container have also an orange border instead of black? And an orange ! sign at right? I thought it from the figma image.
> 
> @TITHI1244 yes..tithi, i did that, when user enter an email like [xyz@gmail.om](mailto:xyz@gmail.om) (not .com), the user will get an orange sign and warning, but i didnt put them for when the user enters continue without entering email,as i am not sure about that case.., but let me know, if have to do something else too, i will do that..!
i tried to attach a pic tithi, link : https://user-images.githubusercontent.com/71669597/115437318-54be5880-a20c-11eb-9d69-5f0996348422.png



-

**Comment by TITHI1244** [comment]
Yes, I get your point @rajanibusani. But what about other errors like a missing '@' or a missing '.'? Then I see the default html form warning, not the orange color customized warning. Maybe using a regex and showing that customized warning for that could solve it. What do you think?

**Comment by rajanibusani** [comment]
> Yes, I get your point @rajanibusani. But what about other errors like a missing '@' or a missing '.'? Then I see the default html form warning, not the orange color customized warning. Maybe using a regex and showing that customized warning for that could solve it. What do you think?

hi @TITHI1244 ...Now i changed the regex pattern, now it will check missing @, ., etc...Thanq

**Comment by sofiiadidovych** [comment]
Good job, @rajanibusani! I looked through your code and storybook, everything works: validation checks work and styles look good.

**Comment by JyothiNandyala** [comment]
Good work @rajanibusani ,i have seen your code and also i run your storybook its looking good.keep it up.

**Comment by ccshah298** [comment]
good work @rajanibusani its looks perfect.. i have seen your storybook code 👍 good job...

**Pull request closed without merging**
