### PR TITLE
removed background image to avoid using twice while it should use in …

### PR DESCRIPTION
**Pull request by soujanyapolavarapu**
# Description

Removed background image.since we use this image for Storybook: Profile Page #110.

Fixes # (issue Profile Quiz Results #108)

# How to test?

npm run storybook

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by sofiiadidovych — APPROVED** [review]
Good job @soujanyapolavarapu!

**Comment by soujanyapolavarapu** [comment]
> Good job @soujanyapolavarapu!

Thankyou @sofiiadidovych

**Review by valmdz — APPROVED** [review]
Seems good :)

**Comment by soujanyapolavarapu** [comment]
> Seems good :)

Thank you @valmdz

**Pull request merged**
