### PR TITLE
Emailform responsiveness

### LINKED ISSUE #66: Storybook: Registration Form (replaces issue #40)
## User story

**Who:** **As a** User
**What:** **I want to** be able to write my email 
**Why:** **so that I can** choose which email I want to register with.

## Acceptance criteria

Create a storybook component for the form below:
image

image

Check the wireframes here: https://www.figma.com/file/9SJRaxPSuPI3lSl8ULNyJ8/GuideIT-For-Developers?node-id=0%3A1

## Implementation details

Use **Knobs** where we can choose  **WIDTH**, **FONTS** like [Roboto](https://fonts.google.com/specimen/Roboto?preview.text=Back&preview.text_type=custom) and [Roboto+Mono](https://fonts.google.com/specimen/Roboto+Mono?preview.text=What%20is%20GuideIT%3F&preview.text_type=custom) and **COLORS** #DB643D, #535C75 and #FFFFFF

### PR DESCRIPTION
**Pull request by rajanibusani**
# Description
Made Email form responsive By changing width from px to %
Please provide a short summary explaining what this PR is about.

Fixes #66 

# How to test?
npm run storybook
Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by soujanyapolavarapu — APPROVED** [review]
Good job dear :) 👍🏻

**Comment by soujanyapolavarapu** [comment]
@dpfernandes please approve this PR so that i can make changes and push for Registration Page storybook component  responsive.

**Review by dpfernandes — APPROVED** [review]
👍

**Comment by rajanibusani** [comment]
> @dpfernandes please approve this PR so that i can make changes and push for Registration Page storybook component responsive.

+1

**Pull request merged**
