### PR TITLE
Profile quiz results

### PR DESCRIPTION
**Pull request by sofiiadidovych**
# I created a storybook for profile quiz results

Fixes # 108

# How to test?

Run npm run storybook

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by soujanyapolavarapu — APPROVED** [review]
Good job @sofiiadidovych 👍🏻

**Comment by soujanyapolavarapu** [comment]
Hi @dpfernandes Please check and approve this PR so that i can use this in profile page.Thank you :)

**Review by dpfernandes — APPROVED** [review]
👍

**Comment by ccshah298** [comment]
good job @sofiiadidovych

**Pull request merged**
