### PR TITLE
deleted extra envelope image and made changes in emailregistration fo…

### PR DESCRIPTION
**Pull request by rajanibusani**
# Description
deleted extra envelope image and made changes in email registartion component

Please provide a short summary explaining what this PR is about.

Fixes #  (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by Enqira — APPROVED** [review]
Right changes have been made.

**Comment by rajanibusani** [comment]
> Right changes have been made.
Thank you @Enqira

**Comment by ccshah298** [comment]
Nice work @rajanibusani 👍

**Review by ccshah298 — APPROVED** [review]

**Review by dpfernandes — APPROVED** [review]
👍

**Review by bytewiz — APPROVED** [review]

**Pull request merged**
