### PR TITLE
add registration page container  storybook component

### PR DESCRIPTION
**Pull request by soujanyapolavarapu**
# Description

This PR is about Storybook: RegistrationPage #100

Fixes # (#100)

# How to test?

npm run storybook
npm run code:lint

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by Enqira — APPROVED** [review]
Looks good :)

**Review by bytewiz — APPROVED** [review]
Seems fine 👌

**Comment by soujanyapolavarapu** [comment]
> Seems fine 👌

Thank You Neils can i merge now :)

**Comment by soujanyapolavarapu** [comment]
> Looks good :)

Thank you @Enqira

**Pull request merged**
