### PR TITLE
Seeding questions table

### LINKED ISSUE #35: Databases: Create Seeding for the Questions Table
## User story

**Who:** **As a** developer
**What:** **I want to** be able to work with Questions
**Why:** **so that we can** create the backend endpoint for Questions

## Acceptance criteria

Create a seeding file that insert these questions into the questions table 

1.  When visiting a website, what is that you are most interested in?
2. I can easily notice changes around me including people, culture, trends, etc.
3. When I have a list of tasks to do, I prefer to multitask rather than focusing on singular tasks one at a time
4. I can easily understand what someone else is going through
5. I work well under pressure

## Implementation details
Read up on the migration and seeds in the readme file. Zaki has created a great video for this - https://www.youtube.com/watch?v=id34_al68x8
When this story is done it should be possible to work with the Questions table and have some Questions in the table. 
You can see the migration and the seeds for the modules. 

image

Please consider the DB Diagram https://github.com/HackYourFuture-CPH/Guide-IT#%EF%B8%8F-database-model-diagram

### PR DESCRIPTION
**Pull request by cph-kiwi**
# Description

This PR is for a file to seed the questions table of the database with a set of data, for the purpose of having some data to test with and see running in development.

Fixes #35
https://github.com/HackYourFuture-CPH/Guide-IT/issues/35

# How to test?

To test this, you need to make sure you have pulled the latest version of develop branch.
In the terminal write npm run db:setup then verify questions table in database.
Then checkout branch seeding-questions-table.
In the terminal write npm run knex -- seed:run then verify that rows have appeared in database table.
Then change back to develop branch and in the terminal write npm run db:clean.
Verify that the questions table has been removed from the database.

# Checklist

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by dpfernandes — CHANGES_REQUESTED** [review]
@cph-kiwi - Why are you adding the modules content on this file questionsTableSeed 2.js?

**Comment by cph-kiwi** [comment]
I have no clue where questionsTableSeed 2.js came from as I didn't create it. I have removed the unnecessary files and updated the PR now.

**Review by qamarfj — APPROVED** [review]
looks good

**Review by dpfernandes — APPROVED** [review]
👍

**Pull request merged**
