### PR TITLE
 i have deleted the unwanted components

### PR DESCRIPTION
**Pull request by JyothiNandyala**
# Description

Removed the unwanted components and containers from the guideit because we are not using them.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by Enqira — APPROVED** [review]
Looks good :)

**Review by rajanibusani — APPROVED** [review]
Good Job @JyothiNandyala

**Review by dpfernandes — APPROVED** [review]
👍

**Review by dpfernandes — APPROVED** [review]
👍

**Pull request merged**
