### PR TITLE
fixed files that don't follow naming convention fourth PR

### PR DESCRIPTION
**Pull request by Enqira**
# Description

renamed files that don't follow naming convention.
Fixes # (issue)

# How to test?
By checking the renamed file names and see if they follow the naming conventioin or not
# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by DlnyaMazhari** [comment]
As per changes I have seen, it looks fine ! 
Good job 👍🏾

**Comment by Enqira** [comment]
Yes Daniel, I wanted to keep this PR short, and I will make a new and last PR to make changes on the container forlder

**Comment by dpfernandes** [comment]
> Yes Daniel, I wanted to keep this PR short, and I will make a new and last PR to make changes on the container forder

OK

**Review by DlnyaMazhari — APPROVED** [review]

**Review by Poorooshka — COMMENTED** [review]
I reviewed the changed names and they seem correct according to the name conventions.

**Pull request merged**
