### PR TITLE
add Create Dummy Pages

### PR DESCRIPTION
**Pull request by soujanyapolavarapu**
# Description

I have created a dummy pages(added folders with respective component files and anded some title in it).

Fixes # (issue)
issue #38

# How to test?
pull my branch dummyPages and check inside containers.

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by dpfernandes — CHANGES_REQUESTED** [review]
Please remove the button related files from this Pull Request

**Review by dpfernandes — APPROVED** [review]
👍

**Review by abedaarabi — APPROVED** [review]
hey @soujanyapolavarapu  very good job, but next time when you create a dummy function (component) please  add props, something like that: 
`const Dummy = (props) => {
  const {   } = props; // here they can add whatever props they want

  return <div>XXXXXXXXXXXXXXX</div>;
};
`
again this is not important just to know :)

**Review by cph-kiwi — APPROVED** [review]

**Review by TITHI1244 — APPROVED** [review]
Nicely done @soujanyapolavarapu  :)

**Comment by soujanyapolavarapu** [comment]
> Nicely done @soujanyapolavarapu :)

Thankyou tithi :)

**Comment by soujanyapolavarapu** [comment]
Closed Create Dummy Pages #38

**Pull request merged**
