### PR TITLE
added shadows for homepage header and homepage buttons

### PR DESCRIPTION
**Pull request by TITHI1244**
# Description

added shadows for homepage header and homepage buttons

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by Poorooshka — CHANGES_REQUESTED** [review]
Thank you Tithi for your hard work. The orange triangle seems too close to the text. and the buttons label (text) on figma are all on one line (I had developed the original button with one line text and shadow) so there might have been additional formatting. I will check it out.

The other issue is when I logout I can not see the "create account" on homepage, which I'm not sure whether is OK.

**Comment by TITHI1244** [comment]
Thanks @Poorooshka for your review. I have created one more PR for those issues, please check. And we do not need create account now as we are only logging in through google account.

**Review by JyothiNandyala — APPROVED** [review]
It's lokks good.

**Review by dpfernandes — APPROVED** [review]
👍

**Review by Poorooshka — APPROVED** [review]

**Pull request merged**
