### PR TITLE
Elevator pitch instruction

### PR DESCRIPTION
**Pull request by sandhana14**
# Description
Created elevator pitch instructions page component

Fixes # (issue)
#106 

# How to test?

Either npm run storybook or add the route for this component in app.js and try

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by sofiiadidovych — APPROVED** [review]
Good job, @sandhana14! Looks good :)

**Review by rajanibusani — COMMENTED** [review]
Good Job @sandhana14

**Review by rajanibusani — APPROVED** [review]

**Comment by ccshah298** [comment]
good job @sandhana14

**Review by ccshah298 — APPROVED** [review]

**Review by bytewiz — APPROVED** [review]
Looks good 👍

**Pull request merged**
