### PR TITLE
Add seed files to production folder

### LINKED ISSUE #183: Create Seeding for the Questions & Answers Table in Production environment
### **User Story**

**Who**: As a Developer
**What**: I want to be able to work with Questions and answers
**Why**: So that we can see the data of question and answer in database of production environment 

### **Acceptance criteria**
Create a seeding files that insert  questions and answers into the questions table and answer table for the production environment .

### **Implementation details**
Read up on the migration and seeds in the readme file. Zaki has created a great video for this - https://www.youtube.com/watch?v=id34_al68x8
When this story is done it should be possible to work with the Questions table and have some Questions in the table.
You can see the migration and the seeds for the modules.

Screenshot 2021-05-23 at 14 56 11

Please consider the DB Diagram https://github.com/HackYourFuture-CPH/Guide-IT#%EF%B8%8F-database-model-diagram

### PR DESCRIPTION
**Pull request by sofiiadidovych**
# Add seed files to the production folder

I added seed files to the production folder (the same as in the development)

Fixes #183

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by qamarfj — COMMENTED** [review]
Hi, great work  @sofiiadidovych . I just want to mention, there are new changes in 01_questions.js please consider them too.

**Review by dpfernandes — CHANGES_REQUESTED** [review]
We are missing the   image_url:          'src/client/assets/images/questionBackgrounds/question1background.png',   and the is_agreement_question: false,

**Comment by sofiiadidovych** [comment]
> too.



> Hi, great work @sofiiadidovych . I just want to mention, there are new changes in 01_questions.js please consider them too.

Thank you @qamarfj for your comment, for some reason I had an old develop. I changed the file

**Comment by sofiiadidovych** [comment]
> We are missing the image_url: 'src/client/assets/images/questionBackgrounds/question1background.png', and the is_agreement_question: false,

@dpfernandes thank you for your comment, I had an old develop, now I changed my files.

**Review by dpfernandes — APPROVED** [review]
👍

**Review by qamarfj — APPROVED** [review]
looks good

**Pull request merged**
