### PR TITLE
Quiz question component

### LINKED ISSUE #12: Storybook: Quiz Question Component
## User story

**Who:** **As a** developer
**What:** **I want to** be have a quiz question component that can take different questions text and different images
**Why:** **so that I can**  use the same component in multiple pages/questions.

## Acceptance criteria

Create a storybook component for the Quiz Answers that meets what's illustrated below:

Screenshot 2021-04-13 at 01 43 16
Screenshot 2021-04-13 at 01 43 08

Check the wireframes here: https://www.figma.com/file/9SJRaxPSuPI3lSl8ULNyJ8/GuideIT-For-Developers?node-id=0%3A1

## Implementation details

Use **Knobs** where we can choose  **Text** for the questions,  and URLs for images.

For the text use like [Roboto](https://fonts.google.com/specimen/Roboto?preview.text=Back&preview.text_type=custom)  and color #FFFFFF and the use the images below that should be added to the folder /src/client/assets/images/

Question 1 - Picture01
picture01

Question 2 - Picture02
picture02

Question 3 - Picture03
picture03

Question 4 - Picture04
picture04

Question 5 - Picture05
picture05

### PR DESCRIPTION
**Pull request by cph-kiwi**
# Description

I have created a quiz question component that can take different question texts and different images. This component is flexible so that it can be adapted through props to display different questions and different ways of answering - either multi choice or agreement scale.

Fixes #12
https://github.com/HackYourFuture-CPH/Guide-IT/issues/12

# How to test?

I added stories for this component so that it can be viewed.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by dpfernandes — COMMENTED** [review]
@cph-kiwi please check if the button developed in this issue solves your need https://github.com/HackYourFuture-CPH/Guide-IT/issues/7 so we avoid having duplicate components. @Poorooshka can you please check the button together with @cph-kiwi ?

**Comment by cph-kiwi** [comment]
@Poorooshka I have commented in the file where these button components are used that they may need to be updated with "official buttons", and the button components I made are easily deleted. Let me know what you want to do (or if I can help in any way).

**Review by qamarfj — APPROVED** [review]
Great work. Component is working in storybook as per requirement. Code is clean and understandable.

**Comment by cph-kiwi** [comment]
@Poorooshka and I have had a chat. I will remove the buttons from this PR.

**Comment by cph-kiwi** [comment]
I have removed the button components.

**Comment by cph-kiwi** [comment]
@aijazraja can you approve this, if you are happy with it?

**Review by TITHI1244 — COMMENTED** [review]
Great job @cph-kiwi. Neat code with easy-to-understand comments.

**Review by aijazraja — APPROVED** [review]

**Comment by wwang107** [comment]
LGTM

**Pull request merged**
