### PR TITLE
Fixed next step page stylings

### PR DESCRIPTION
**Pull request by sandhana14**
# Description

Fixed next step page stylings

Fixes # (issue)
#228 

# How to test?

npm run dev

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by rajanibusani — APPROVED** [review]
Good job @sandhana14

**Review by Poorooshka — APPROVED** [review]
Looks good to me!

**Review by ccshah298 — APPROVED** [review]
good job👍

**Review by valmdz — COMMENTED** [review]
Try to be consistent with the units you use, you can read more about units in [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units). Overall it is best to use relative units rather than absolute units. At least try to keep consistency for the things that serve the fame purpose, so fx. distances, widths, font-sizes etc.

The `top` and `left` properties and `translate` one serve a similar purpose, so you are moving the elements in the X and Y direction with both properties, plus in some cases, you add an extra distance with the `margin`. Do you need to do this?

On line 60 and 61 an image is being modified on `width` and `height`, just choose one. It is best practice, otherwise you might end up distorting the image.

**Comment by sandhana14** [comment]
> Try to be consistent with the units you use, you can read more about units in [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units). Overall it is best to use relative units rather than absolute units. Try to keep consistency for the things that serve the same purpose, so fx. distances, widths, font-sizes etc.
> 
> The `top` and `left` properties and `translate` one serve a similar purpose, so you are moving the elements in the X and Y direction with both properties, plus in some cases, you add an extra distance with the `margin`. Do you need to do this?
> 
> On line 60 and 61 an image is being modified on `width` and `height`, just choose one. It is best practice, otherwise you might end up distorting the image.

Hi Valentina, Thank you so much for your review. What you have mentioned, I also agree with you. If I have to consider all these changes, I have to change most of the next step page CSS. For that, I have to discuss with the person who actually did the whole page. Because Currently I changed only the button styles and gave some responsiveness. Please kindly let me know What should I do now?

**Review by JyothiNandyala — APPROVED** [review]
Hi sandhana i have checked its looking perfectly, Good job.

**Review by valmdz — COMMENTED** [review]
It is much better now, well done @sandhana14

**Review by valmdz — APPROVED** [review]

**Pull request merged**
