### PR TITLE
fixed child key warning

### PR DESCRIPTION
**Pull request by qamarfj**
# Description

I have fixed  child key missing warnings in CareerPage and QuizResultPage container.  

Fixes # (issue) there is no open issue for it.

# How to test?

please run npm run dev and visit this links: http://localhost:3000/quiz-results/1 and http://localhost:3000/career/UX%20designer 
in console check for warnings.

# Checklist

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by Enqira — APPROVED** [review]
As it should be. Great

**Review by aijazraja — APPROVED** [review]

**Review by TITHI1244 — APPROVED** [review]
Thanks @qamarfj. Good job :)

**Review by cph-kiwi — APPROVED** [review]
Perfect.

**Review by dpfernandes — APPROVED** [review]
👍

**Pull request merged**
