### PR TITLE
Authenticated user can answer questions

### LINKED ISSUE #137: Full Stack: Quiz Flow
## User story

**Who:** **As a** developer 
**What:** **I want to** save every answer of the quiz whenever the user press NEXT on the Quiz.
**Why:** **so that we can** that we in the end of the quiz we can calculate the career result and path.

## Implementation details for the page
If the user is not authenticated, we need to create a new entry on the User's table but with firebase_token value = "anonymous ", and retrieve that value so that we can use it to save it in the DB.

Whenever a question is answered we make a call using the endpoint Quiz Result and we add a new Quiz result answer (answer id) to a specific question(question id), and we also need to write which user is answering (user_id) - check endpoint developed here https://github.com/HackYourFuture-CPH/Guide-IT/issues/34

Remember to split the story into smaller PR's! Maybe you can do a PR with just the words, filter fx. You can also choose to do it in separate commits. just be very aware of the PR's not becoming too big!

Check the README file here https://github.com/HackYourFuture-CPH/guide-it#-working-with-api-documentation---swagger and this article should also help you with that https://blog.logrocket.com/documenting-your-express-api-with-swagger/

### PR DESCRIPTION
**Pull request by cph-kiwi**
# Description

This allows an authenticated user to answer the questions with the correct answer entries into the quiz-results table. 

Fixes #137 

# How to test?

Open branch and run "npm run dev". Authenticate, and follow quiz through.

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by sofiiadidovych — COMMENTED** [review]
@cph-kiwi thank you so much for your work!
I have a question: I signed up with my google account, went to the quiz section, and when I try to press NEXT button nothing happens: 
image
Is it the same for you?

**Review by qamarfj — COMMENTED** [review]
Its same for me as @sofiiadidovych mentioned.

**Comment by cph-kiwi** [comment]
Yes, that is fixed in the next PR. All the functionality for the button was added there. This is just for authentication.

**Review by qamarfj — APPROVED** [review]
👍

**Review by rajanibusani — APPROVED** [review]
Its Working Nicely, You really did a great job Beth 👏 👏  @cph-kiwi

**Review by valmdz — APPROVED** [review]

**Pull request merged**
