### PR TITLE
added files for users gmail sign/signup with firebase

### PR DESCRIPTION
**Pull request by rajanibusani**
# Description
Gmail signup/signin by using firebase

Please provide a short summary explaining what this PR is about.

Fixes # (issue)

# How to test?
sign up in the registration page, /registration 
npm run dev

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by TITHI1244 — APPROVED** [review]
A very big thanks for your patience, @rajanibusani. I saw it working perfectly now :)

**Review by bytewiz — DISMISSED** [review]
Please check the lint errors

**Comment by rajanibusani** [comment]
> Please check the lint errors

HI @bytewiz  Niels, i checked it, i have two errors, and i have a doubt authRedirect function, if possible i want to clarify with you,

**Comment by rajanibusani** [comment]
> > Please check the lint errors
> 
> HI @bytewiz Niels, i checked it, i have two errors, and i have a doubts about them and  authRedirect function, if possible i want to clarify with you,

**Review by dpfernandes — APPROVED** [review]
👍

**Pull request merged**
