### PR TITLE
added My profile to home page

### PR DESCRIPTION
**Pull request by rajanibusani**
# Description
Added My profile to home, if user is logged in, and also in profile page changed the end point, which we are using to get the user deatiles.
Please provide a short summary explaining what this PR is about.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by DlnyaMazhari — APPROVED** [review]
Good job @rajanibusani  👍🏾  I ran the app, and when I log in and click back button to home, it shows my profile which by clicking you will see your profile again. 
It makes more sense now and thanks. :)

**Review by sandhana14 — APPROVED** [review]
Hello @rajanibusani . It is working perfectly now. Now, the user can easily see whether the user is logged in or not , when the user is on the homepage by seeing My Profile. That's great. Good job 👍

**Comment by rajanibusani** [comment]
> Good job @rajanibusani 👍🏾 I ran the app, and when I log in and click back button to home, it shows my profile which by clicking you will see your profile again.
> It makes more sense now and thanks. :)

Thank You @DlnyaMazhari

**Comment by rajanibusani** [comment]
> Hello @rajanibusani . It is working perfectly now. Now, the user can easily see whether the user is logged in or not , when the user is on the homepage by seeing My Profile. That's great. Good job

**Comment by rajanibusani** [comment]
Mistakenly i closed the PR

**Pull request closed without merging**
