### PR TITLE
Added auth.currentUser check

### PR DESCRIPTION
**Pull request by cph-kiwi**
# Description

The Next button was not working for unauthenticated users of the quiz page after they had selected an answer. The problem should be fixed now.

Fixes # https://github.com/HackYourFuture-CPH/Guide-IT/issues/219

# How to test?

Open the branch, run "npm run dev", then follow the quiz through as an unauthenticated user.

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by rajanibusani — APPROVED** [review]
Now its working perfectly @cph-kiwi

**Comment by ditlevHYF** [comment]
This does not work for me. If im logged in i can go through the test, but if im not logged ind, nothing happens when i press next. I get the following response from the API error 403 'error	"Forbidden"'

**Comment by cph-kiwi** [comment]
Ok @ditlevHYF . I'll check it out.

**Review by Enqira — APPROVED** [review]

**Comment by Enqira** [comment]
Tested it, works as it should for me.

**Review by dpfernandes — APPROVED** [review]
👍

**Pull request merged**
