### PR TITLE
changed button styles in career component

### PR DESCRIPTION
**Pull request by TITHI1244**
# Description

Changed button styles in career component

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by qamarfj — APPROVED** [review]

**Comment by JyothiNandyala** [comment]
I have checked it looks perfect.

**Review by JyothiNandyala — APPROVED** [review]
👍

**Review by sandhana14 — APPROVED** [review]
Good Job @TITHI1244

**Review by dpfernandes — APPROVED** [review]
👍

**Pull request merged**
